-- =============================================
-- Argos Evidence Management System
-- Authentication Stored Procedures
-- Description: Database operations for user authentication
-- Author: Argos Development Team
-- Version: 1.0
-- =============================================

-- =============================================
-- Procedure: sp_get_user_by_username
-- Description: Retrieves a user by username for authentication
--
-- What it does:
--   1. Searches for a user by username
--   2. Only returns active users
--   3. Returns all necessary fields for authentication
--
-- Parameters:
--   p_username: Username to search for
--
-- Returns: User record or empty if not found
--
-- Example usage:
--   SELECT * FROM sp_get_user_by_username('tech01');
-- =============================================
CREATE OR REPLACE FUNCTION sp_get_user_by_username(
  p_username VARCHAR(50)
)
RETURNS TABLE (
  user_id INTEGER,
  username VARCHAR(50),
  email VARCHAR(255),
  password_hash VARCHAR(255),
  full_name VARCHAR(255),
  role VARCHAR(50),
  is_active BOOLEAN,
  created_at TIMESTAMP
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    u.user_id,
    u.username,
    u.email,
    u.password_hash,
    u.full_name,
    u.role,
    u.is_active,
    u.created_at
  FROM users u
  WHERE u.username = p_username;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION sp_get_user_by_username IS 'Retrieves user by username for authentication purposes.';


-- =============================================
-- Procedure: sp_get_user_by_id
-- Description: Retrieves a user by ID (for token verification)
--
-- What it does:
--   1. Searches for a user by ID
--   2. Only returns active users
--   3. Does NOT return password_hash for security
--
-- Parameters:
--   p_user_id: User ID to search for
--
-- Returns: User record without password or empty if not found
--
-- Example usage:
--   SELECT * FROM sp_get_user_by_id(1);
-- =============================================
CREATE OR REPLACE FUNCTION sp_get_user_by_id(
  p_user_id INTEGER
)
RETURNS TABLE (
  user_id INTEGER,
  username VARCHAR(50),
  email VARCHAR(255),
  full_name VARCHAR(255),
  role VARCHAR(50),
  is_active BOOLEAN,
  created_at TIMESTAMP
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    u.user_id,
    u.username,
    u.email,
    u.full_name,
    u.role,
    u.is_active,
    u.created_at
  FROM users u
  WHERE u.user_id = p_user_id AND u.is_active = TRUE;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION sp_get_user_by_id IS 'Retrieves user by ID without password hash for security.';


-- =============================================
-- Procedure: sp_register_user
-- Description: Registers a new user in the system
--
-- What it does:
--   1. Validates username uniqueness
--   2. Validates email uniqueness
--   3. Creates new user record
--   4. Returns the new user_id
--
-- Parameters:
--   p_username: Unique username
--   p_email: Unique email address
--   p_password_hash: Already hashed password (bcrypt)
--   p_full_name: User's full name
--   p_role: User role (technician, coordinator, admin)
--
-- Returns: INTEGER (new user_id)
--
-- Business Rules:
--   - Username must be unique
--   - Email must be unique and valid format
--   - Password hash should be generated by application layer
--   - Role must be one of: technician, coordinator, admin
--
-- Example usage:
--   SELECT sp_register_user('newuser', 'user@email.com', '$2b$10$hash...', 'New User', 'technician');
-- =============================================
CREATE OR REPLACE FUNCTION sp_register_user(
  p_username VARCHAR(50),
  p_email VARCHAR(255),
  p_password_hash VARCHAR(255),
  p_full_name VARCHAR(255),
  p_role VARCHAR(50)
)
RETURNS INTEGER AS $$
DECLARE
  v_user_id INTEGER;
BEGIN
  -- Validate username
  IF p_username IS NULL OR TRIM(p_username) = '' THEN
    RAISE EXCEPTION 'Username is required';
  END IF;

  IF LENGTH(TRIM(p_username)) < 3 THEN
    RAISE EXCEPTION 'Username must be at least 3 characters long';
  END IF;

  -- Check if username already exists
  IF EXISTS (SELECT 1 FROM users WHERE username = p_username) THEN
    RAISE EXCEPTION 'Username already exists';
  END IF;

  -- Validate email
  IF p_email IS NULL OR TRIM(p_email) = '' THEN
    RAISE EXCEPTION 'Email is required';
  END IF;

  -- Check if email already exists
  IF EXISTS (SELECT 1 FROM users WHERE email = p_email) THEN
    RAISE EXCEPTION 'Email already registered';
  END IF;

  -- Validate full_name
  IF p_full_name IS NULL OR TRIM(p_full_name) = '' THEN
    RAISE EXCEPTION 'Full name is required';
  END IF;

  -- Validate role
  IF p_role NOT IN ('technician', 'coordinator', 'admin') THEN
    RAISE EXCEPTION 'Invalid role. Must be technician, coordinator, or admin';
  END IF;

  -- Insert new user
  INSERT INTO users (username, email, password_hash, full_name, role)
  VALUES (TRIM(p_username), TRIM(p_email), p_password_hash, TRIM(p_full_name), p_role)
  RETURNING users.user_id INTO v_user_id;

  RETURN v_user_id;

EXCEPTION
  WHEN unique_violation THEN
    RAISE EXCEPTION 'Username or email already exists';
  WHEN OTHERS THEN
    RAISE EXCEPTION 'Error registering user: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION sp_register_user IS 'Registers a new user with validation. Password must be pre-hashed.';


-- =============================================
-- Procedure: sp_update_user_password
-- Description: Updates a user's password
--
-- What it does:
--   1. Validates user exists and is active
--   2. Updates password hash
--
-- Parameters:
--   p_user_id: User ID
--   p_new_password_hash: New hashed password
--
-- Returns: BOOLEAN (success)
--
-- Example usage:
--   SELECT sp_update_user_password(1, '$2b$10$newhash...');
-- =============================================
CREATE OR REPLACE FUNCTION sp_update_user_password(
  p_user_id INTEGER,
  p_new_password_hash VARCHAR(255)
)
RETURNS BOOLEAN AS $$
BEGIN
  -- Check if user exists and is active
  IF NOT EXISTS (SELECT 1 FROM users WHERE user_id = p_user_id AND is_active = TRUE) THEN
    RAISE EXCEPTION 'User not found or inactive';
  END IF;

  -- Update password
  UPDATE users
  SET password_hash = p_new_password_hash,
      updated_at = CURRENT_TIMESTAMP
  WHERE user_id = p_user_id;

  RETURN TRUE;

EXCEPTION
  WHEN OTHERS THEN
    RAISE EXCEPTION 'Error updating password: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION sp_update_user_password IS 'Updates user password. New password must be pre-hashed.';


-- =============================================
-- Procedure: sp_get_all_users
-- Description: Retrieves all active users (for admin purposes)
--
-- What it does:
--   1. Returns all active users
--   2. Does NOT return password hashes
--   3. Can filter by role
--
-- Parameters:
--   p_role: Optional role filter (NULL for all users)
--
-- Returns: List of users without password hashes
--
-- Example usage:
--   SELECT * FROM sp_get_all_users(NULL);       -- All users
--   SELECT * FROM sp_get_all_users('technician'); -- Only technicians
-- =============================================
CREATE OR REPLACE FUNCTION sp_get_all_users(
  p_role VARCHAR(50) DEFAULT NULL
)
RETURNS TABLE (
  user_id INTEGER,
  username VARCHAR(50),
  email VARCHAR(255),
  full_name VARCHAR(255),
  role VARCHAR(50),
  is_active BOOLEAN,
  created_at TIMESTAMP
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    u.user_id,
    u.username,
    u.email,
    u.full_name,
    u.role,
    u.is_active,
    u.created_at
  FROM users u
  WHERE u.is_active = TRUE
    AND (p_role IS NULL OR u.role = p_role)
  ORDER BY u.created_at DESC;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION sp_get_all_users IS 'Retrieves all active users, optionally filtered by role.';


-- =============================================
-- Success message
-- =============================================
DO $$
BEGIN
  RAISE NOTICE '✅ Authentication stored procedures created successfully!';
  RAISE NOTICE '🔐 Procedures created:';
  RAISE NOTICE '   - sp_get_user_by_username';
  RAISE NOTICE '   - sp_get_user_by_id';
  RAISE NOTICE '   - sp_register_user';
  RAISE NOTICE '   - sp_update_user_password';
  RAISE NOTICE '   - sp_get_all_users';
END $$;
